### ISSUE TITLE
Builder passes target atoms through unquoted

### ISSUE THREAD

**Issue by optiz0r** [Sabayon/devkit#13]
builder passes the target atoms through to emerge unquoted which means special characters such as "<" and ">" used for versioned atoms are treated as bash special characters. This breaks the build and is a potential security risk.

Builder should quote all targets arguments.

**Comment by mudler** [comment]
Fixed in https://github.com/Sabayon/devkit/commit/5a3be7c0f15a2a48e40cecb7d8d3102611bfd801 , now should support those as well.
