### ISSUE TITLE
Outdated docker sabayon/eit-amd64 image

### ISSUE THREAD

**Issue by welele08** [Sabayon/devkit#20]
The eit-amd64 image is running on base-gcc-6.4.0-r1, which give bad dependancy tree when using sabayon-createrepo. All new package depend raise an "unmet dependancy : sys-devel/base-gcc-6.4.0" on equo install.

**Comment by geaaru** [comment]
Hi welele08,

currently, we don't support any more `sabayon/eit-amd64`. Please, use `sabayon/builder` (or old `sabayon/builder-amd64`) that is the image used by us to build scr repos.
